[azureEntraId]
authorization_endpoint = "https://<auth_provider_url>/oauth2/v2.0/authorize"
token_endpoint = "https://<auth_provider_url>/oauth2/v2.0/token"
redirect_uri = "<This app's url>"
client_id = "<Client id>"
audience = "<Audience>"
client_secret = "<Client secret>"
scope = "<Scope(s)>"
identity_field_in_token = "<Identity field in token(sub etc.)>"
jwks_uri = "<JWKS Uri>"